/**
 * tauri.ts — Typed wrappers over the Tauri IPC command surface.
 *
 * The frontend NEVER handles raw cryptographic material. These functions
 * are the only mechanism by which the UI communicates with the Rust backend.
 * All error handling is propagated via rejected promises with string payloads.
 */
import { invoke } from "@tauri-apps/api/core";

export interface CredentialEntry {
  id: string;
  service: string;
  username: string;
  password: string;
  notes: string;
  created_at: number;
  updated_at: number;
}

export interface VaultStatus {
  vault_exists: boolean;
  is_unlocked: boolean;
  failed_attempts: number;
  lockout_remaining_secs: number;
}

/** Returns vault existence + lock state. Call on every mount. */
export async function getVaultStatus(): Promise<VaultStatus> {
  return invoke<VaultStatus>("get_vault_status");
}

/**
 * Creates a new vault using the provided master and canary passphrases.
 * Both passphrases are generated by the frontend via generatePassphrase()
 * and presented to the user before this call is made.
 */
export async function setupVault(passphrase: string, canaryPassphrase: string): Promise<void> {
  return invoke<void>("setup_vault", { passphrase, canaryPassphrase });
}

/**
 * Attempts to unlock the vault with the given passphrase.
 * Throws "LOCKED:<secs>" if currently in lockout.
 * Throws "WRONG_PASSPHRASE" on authentication failure.
 */
export async function unlockVault(passphrase: string): Promise<void> {
  return invoke<void>("unlock_vault", { passphrase });
}

/** Locks the vault and zeroizes the master key in Rust. */
export async function lockVault(): Promise<void> {
  return invoke<void>("lock_vault");
}

/** Returns all decrypted credential entries. Requires unlocked vault. */
export async function getCredentials(): Promise<CredentialEntry[]> {
  return invoke<CredentialEntry[]>("get_credentials");
}

/** Adds a credential and immediately re-encrypts the vault. Returns the new entry ID. */
export async function addCredential(
  service: string,
  username: string,
  password: string,
  notes: string
): Promise<string> {
  return invoke<string>("add_credential", { service, username, password, notes });
}

/** Removes a credential by ID and immediately re-encrypts. */
export async function deleteCredential(id: string): Promise<void> {
  return invoke<void>("delete_credential", { id });
}

/** Generates a fresh Diceware passphrase (without creating a vault). */
export async function generatePassphrase(): Promise<string> {
  return invoke<string>("generate_passphrase");
}

/** Generates a high-entropy account password of the given length (12–128). */
export async function generateSecurePassword(length?: number): Promise<string> {
  return invoke<string>("cmd_generate_secure_password", { length });
}
