/**
 * tauri.ts — Typed wrappers over the Tauri IPC command surface.
 *
 * The frontend NEVER handles raw cryptographic material. These functions
 * are the only mechanism by which the UI communicates with the Rust backend.
 * All error handling is propagated via rejected promises with string payloads.
 */
import { invoke } from "@tauri-apps/api/core";

export interface PasswordHistoryEntry {
  password: string;
  created_at: number;
  retired_at: number;
}

export interface CredentialEntry {
  id: string;
  service: string;
  username: string;
  password: string;
  notes: string;
  created_at: number;
  updated_at: number;
  password_history: PasswordHistoryEntry[];
  category?: string;
}

export interface NoteFolder {
  id: string;
  name: string;
  created_at: number;
}

export interface SecureNote {
  id: string;
  title: string;
  content: string;
  folder_id?: string;
  is_pinned: boolean;
  created_at: number;
  updated_at: number;
}

export interface VaultStatus {
  vault_exists: boolean;
  is_unlocked: boolean;
  failed_attempts: number;
  lockout_remaining_secs: number;
  is_corrupted: boolean;
}

export interface MlScoreResult {
  label: string;
  nll: number;
  color_hint: string;
  char_count: number;
}

/** Returns vault existence + lock state. Call on every mount. */
export async function getVaultStatus(): Promise<VaultStatus> {
  return invoke<VaultStatus>("get_vault_status");
}

/**
 * Creates a new vault using the provided master and canary passphrases.
 * Both passphrases are generated by the frontend via generatePassphrase()
 * and presented to the user before this call is made.
 */
export async function setupVault(passphrase: string, canaryPassphrase: string): Promise<void> {
  return invoke<void>("setup_vault", { passphrase, canaryPassphrase });
}

/**
 * Attempts to unlock the vault with the given passphrase.
 * Throws "LOCKED:<secs>" if currently in lockout.
 * Throws "WRONG_PASSPHRASE" on authentication failure.
 */
export async function unlockVault(passphrase: string): Promise<void> {
  return invoke<void>("unlock_vault", { passphrase });
}

/** Locks the vault and zeroizes the master key in Rust. */
export async function lockVault(): Promise<void> {
  return invoke<void>("lock_vault");
}

/** Evaluates password strength using the Python ML engine */
export async function checkPasswordStrength(password: string): Promise<MlScoreResult> {
  return invoke<MlScoreResult>("check_password_strength", { password });
}

/** Returns all decrypted credential entries. Requires unlocked vault. */
export async function getCredentials(): Promise<CredentialEntry[]> {
  return invoke<CredentialEntry[]>("get_credentials");
}

/** Adds a credential and immediately re-encrypts the vault. Returns the new entry ID. */
export async function addCredential(
  service: string,
  username: string,
  password: string,
  notes: string,
  category?: string
): Promise<string> {
  return await invoke("add_credential", { service, username, password, notes, category });
}

/** Edits a credential by ID, pushes old password to history if changed, and re-encrypts. */
export async function editCredential(
  id: string,
  service: string,
  username: string,
  password: string,
  notes: string,
  category?: string
): Promise<void> {
  await invoke("edit_credential", { id, service, username, password, notes, category });
}

/** Removes a credential by ID and immediately re-encrypts. */
export async function deleteCredential(id: string): Promise<void> {
  return invoke<void>("delete_credential", { id });
}

/** Deletes a password history entry for a given credential ID. */
export async function deleteHistoryEntry(id: string, retiredAt: number): Promise<void> {
  return invoke<void>("delete_history_entry", { id, retiredAt });
}

// ---------------------------------------------------------------------------
// Secure Notes APIs
// ---------------------------------------------------------------------------

export async function getNotes(): Promise<SecureNote[]> {
  return invoke<SecureNote[]>("get_notes");
}

export async function addNote(
  title: string,
  content: string,
  folder_id: string | null,
  is_pinned: boolean
): Promise<string> {
  return await invoke("add_note", { title, content, folderId: folder_id, isPinned: is_pinned });
}

export async function editNote(
  id: string,
  title: string,
  content: string,
  folder_id: string | null,
  is_pinned: boolean
): Promise<void> {
  return await invoke("edit_note", { id, title, content, folderId: folder_id, isPinned: is_pinned });
}

export async function deleteNote(id: string): Promise<void> {
  return await invoke("delete_note", { id });
}

// ---------------------------------------------------------------------------
// Note Folders APIs
// ---------------------------------------------------------------------------

export async function getNoteFolders(): Promise<NoteFolder[]> {
  return invoke<NoteFolder[]>("get_note_folders");
}

export async function addNoteFolder(name: string): Promise<string> {
  return await invoke("add_note_folder", { name });
}

export async function editNoteFolder(id: string, name: string): Promise<void> {
  return await invoke("edit_note_folder", { id, name });
}

export async function deleteNoteFolder(id: string): Promise<void> {
  return await invoke("delete_note_folder", { id });
}

/** Generates a fresh Diceware passphrase. */
export async function generatePassphrase(wordCount: number, languages: string[]): Promise<string> {
  return invoke<string>("generate_passphrase", { wordCount, languages });
}

/** Generates a high-entropy account password of the given length (12–128). */
export async function generateSecurePassword(length?: number): Promise<string> {
  return invoke<string>("cmd_generate_secure_password", { length });
}

/** Exports the encrypted vault to a file. */
export async function exportVault(exportPath: string): Promise<void> {
  return invoke<void>("export_vault", { exportPath });
}

/** Imports an encrypted vault from a file. */
export async function importVault(importPath: string, oldPassphrase: string): Promise<void> {
  await invoke("import_vault", { importPath, oldPassphrase });
}

/** Exports the vault using Steganography (EOF or LSB) into a carrier image. */
export async function exportStegoVault(carrierPath: string, destPath: string, mode: string): Promise<void> {
  await invoke("export_stego_vault", { carrierPath, destPath, mode });
}

/** Imports a Steganographic vault from a carrier image. */
export async function importStegoVault(sourcePath: string, oldPassphrase: string, mode: string): Promise<void> {
  await invoke("import_stego_vault", { sourcePath, oldPassphrase, mode });
}

/** Securely copies text to the OS clipboard, bypassing clipboard history on Windows. */
export async function secureCopy(text: string): Promise<void> {
  await invoke("secure_copy", { text });
}

/** Gets the application version. */
export async function getAppVersion(): Promise<string> {
  return invoke<string>("get_app_version");
}
